CREATE TABLE IF NOT EXISTS public.censo_escolas_privadas_ativas (
  nu_ano_censo integer NOT NULL,
  no_municipio varchar(150),
  co_municipio integer,
  no_entidade varchar(100),
  co_entidade integer NOT NULL,
  co_rede integer NOT NULL,
  tp_dependencia integer,
  tp_categoria_escola_privada integer,
  tp_localizacao integer,
  tp_localizacao_diferenciada integer,
  tp_situacao_funcionamento integer NOT NULL,
  in_biblioteca integer,
  in_biblioteca_sala_leitura integer,
  in_laboratorio_ciencias integer,
  in_laboratorio_informatica integer,
  in_patio_coberto integer,
  in_patio_descoberto integer,
  in_parque_infantil integer,
  in_piscina integer,
  in_quadra_esportes integer,
  in_quadra_esportes_coberta integer,
  in_quadra_esportes_descoberta integer,
  in_sala_atelie_artes integer,
  in_sala_musica_coral integer,
  in_sala_estudio_danca integer,
  in_sala_multiuso integer,
  in_sala_estudio_gravacao integer,
  in_sala_leitura integer,
  in_sala_atendimento_especial integer,
  in_terreirao integer,
  in_viveiro integer,
  qt_salas_utilizadas integer,
  qt_salas_utiliza_climatizadas integer,
  qt_salas_utilizadas_acessiveis integer,
  in_equip_dvd integer,
  qt_equip_dvd integer,
  in_equip_som integer,
  qt_equip_som integer,
  in_equip_tv integer,
  qt_equip_tv integer,
  in_equip_lousa_digital integer,
  qt_equip_lousa_digital integer,
  in_equip_multimidia integer,
  qt_equip_multimidia integer,
  in_desktop_aluno integer,
  qt_desktop_aluno integer,
  in_comp_portatil_aluno integer,
  qt_comp_portatil_aluno integer,
  in_tablet_aluno integer,
  qt_tablet_aluno integer,
  in_internet_aprendizagem integer,
  in_material_ped_multimidia integer,
  in_material_ped_infantil integer,
  in_material_ped_cientifico integer,
  in_material_ped_difusao integer,
  in_material_ped_musical integer,
  in_material_ped_jogos integer,
  in_material_ped_artisticas integer,
  in_material_ped_profissional integer,
  in_material_ped_desportiva integer,
  in_material_ped_indigena integer,
  in_material_ped_etnico integer,
  in_material_ped_campo integer,
  in_material_ped_bil_surdos integer,
  in_material_ped_agricola integer,
  in_material_ped_quilombola integer,
  in_material_ped_edu_esp integer,
  in_material_ped_nenhum integer,
  in_material_esp_quilombola integer,
  in_material_esp_indigena integer,
  in_material_esp_nao_utiliza integer,
  in_exame_selecao integer,
  in_reserva_ppi integer,
  in_reserva_renda integer,
  in_reserva_publica integer,
  in_reserva_pcd integer,
  in_reserva_outros integer,
  in_reserva_nenhuma integer,
  in_redes_sociais integer,
  in_espaco_atividade integer,
  in_espaco_equipamento integer,
  in_orgao_ass_pais integer,
  in_orgao_ass_pais_mestres integer,
  in_orgao_conselho_escolar integer,
  in_orgao_gremio_estudantil integer,
  in_orgao_outros integer,
  in_orgao_nenhum integer,
  in_educ_ambiental integer,
  in_educ_amb_conteudo integer,
  in_educ_amb_curricular integer,
  in_educ_amb_eixo integer,
  in_educ_amb_eventos integer,
  in_educ_amb_projetos integer,
  in_educ_amb_nenhuma integer,
  tp_aee integer,
  in_mediacao_presencial integer,
  in_mediacao_semipresencial integer,
  in_mediacao_ead integer,
  in_especial_exclusiva integer,
  in_regular integer,
  in_eja integer,
  in_comum_creche integer,
  in_comum_pre integer,
  in_comum_fund_ai integer,
  in_comum_fund_af integer,
  in_comum_medio_medio integer,
  in_comum_medio_integrado integer,
  in_comum_medio_fic integer,
  in_comum_medio_normal integer,
  in_esp_exclusiva_creche integer,
  in_esp_exclusiva_pre integer,
  in_esp_exclusiva_fund_ai integer,
  in_esp_exclusiva_fund_af integer,
  in_esp_exclusiva_medio_medio integer,
  in_esp_exclusiva_medio_integr integer,
  in_esp_exclusiva_medio_fic integer,
  in_esp_exclusiva_medio_normal integer,
  in_comum_eja_fund integer,
  in_comum_eja_medio integer,
  in_comum_eja_prof integer,
  in_esp_exclusiva_eja_fund integer,
  in_esp_exclusiva_eja_medio integer,
  in_esp_exclusiva_eja_prof integer,
  in_comum_prof integer,
  in_esp_exclusiva_prof integer,
  imported_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT censo_escolas_privadas_ativas_pk PRIMARY KEY (nu_ano_censo, co_entidade),
  CONSTRAINT censo_escolas_privadas_ativas_rede_chk CHECK (co_rede = 2),
  CONSTRAINT censo_escolas_privadas_ativas_situacao_chk CHECK (tp_situacao_funcionamento = 1)
);

CREATE INDEX IF NOT EXISTS idx_censo_escolas_privadas_ativas_municipio ON public.censo_escolas_privadas_ativas (co_municipio);
CREATE INDEX IF NOT EXISTS idx_censo_escolas_privadas_ativas_categoria ON public.censo_escolas_privadas_ativas (tp_categoria_escola_privada);
CREATE INDEX IF NOT EXISTS idx_censo_escolas_privadas_ativas_localizacao ON public.censo_escolas_privadas_ativas (tp_localizacao);

GRANT SELECT ON public.censo_escolas_privadas_ativas TO authenticated;
GRANT ALL ON public.censo_escolas_privadas_ativas TO service_role;

ALTER TABLE public.censo_escolas_privadas_ativas ENABLE ROW LEVEL SECURITY;

CREATE POLICY censo_escolas_privadas_select_autenticado
  ON public.censo_escolas_privadas_ativas
  FOR SELECT TO authenticated
  USING (auth.uid() IS NOT NULL);